services:
  rewards-farmer:
    image: juangra87/ms-farmer:latest
    container_name: rewards
    shm_size: 4gb
    command: bash -c 'python3 main.py'
    volumes:
      - ./accounts.json:/app/accounts.json
      - ./logs:/app/logs
    restart: always
